apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-ssl-cert: arn:aws:acm:ap-south-1:835518098452:certificate/e7bba1e7-a2fa-4c6c-84c0-499ae5211ebf
    service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
    
  finalizers:
  - service.k8s.aws/resources
  name: prometheus-lb
  namespace: prometheus-pop-prod
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.100.221.58
  clusterIPs:
  - 10.100.221.58
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  loadBalancerClass: service.k8s.aws/nlb
  ports:
  - name: http
    nodePort: 30184
    port: 80
    protocol: TCP
    targetPort: 9090
  - name: https
    nodePort: 30871
    port: 443
    protocol: TCP
    targetPort: 9090
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - hostname: k8s-promethe-promethe-466ac2e02c-22348c931c080b63.elb.ap-south-1.amazonaws.com
