alertmanager:
  config:
    global:
      resolve_timeout: 15m
    route:
      receiver: 'zenduty'
    receivers:
      - name: 'zenduty'
        webhook_configs:
          - url: ''
server:
  persistentVolume:
    size: 30Gi
serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['kube-state-metrics.monitoring-aws-service.svc.cluster.local:8080']
      # - job_name: 'all_services'
      #   kubernetes_sd_configs:
      #     - role: service
    
  alerting_rules.yml:
    groups:
      - name: Prometheus Alerts
        rules:
          - alert: DeploymentZeroPodsReady
            expr: kube_deployment_spec_replicas{namespace="pop-stage"} > 0 and kube_deployment_status_replicas_available{namespace="pop-stage"} == 0
            for: 5m
            labels:
            annotations:
              summary: "Deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} has no ready pods"
              description: "The deployment desires {{ $value }} replicas but has 0 ready. This may indicate a rollout failure, pod crashes, or resource issues."
#helm upgrade prometheus prometheus-community/prometheus -f values-zenduty-stage.yaml --namespace monitoring-aws-services